import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "../styles/Home.module.css";
const MediumEditor = dynamic(() => import("./Editor"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Draft Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MediumEditor />
    </div>
  );
}
