import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MediumEditor from "./Editor";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Draft Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MediumEditor />
    </div>
  );
}
